version: "3"
services:
  postgres:
    image: "postgres"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: "marten_user"
      POSTGRES_PASSWORD: "marten_pass"
      POSTGRES_DB: "marten_test"
